@startuml

package open_cl {
    class context
    class program
}

class lexer
package "OpenCL Device" <<Rectangle>> {
class "lexer" as lexerKernel << (K,#FF7700) >> 
}

lexer --> lexerKernel
lexer -up-> context
lexer -up-> program

hide members

@enduml